swagger: "2.0"
info:
  version: "0.0.1"
  title: Simple Post Call with Apigee-127
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/x-www-form-urlencoded
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config: {}
x-a127-services: {}
paths:
  /pet:
    # binds a127 app logic to a route
    x-swagger-router-controller: pet_store
    x-a127-apply: {}
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: createPet
      parameters:
        - name: id
          in: formData
          description: The id of the dog
          required: false
          type: string
        - name: pid
          in: query
          description: The cid of the dog
          required: false
          type: string  
        - name: name
          in: formData
          description: The name of the dog
          required: false
          type: string
      responses:
        "200":
          description: Pet Created
          schema:
            # a pointer to a definition
            $ref: "#/definitions/PetCreatedResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  PetCreatedResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
